### ISSUE TITLE
[BUG] Home 페이지 화면 깜빡임

### ISSUE THREAD

**Issue by intersoom** [yourssu/autumn-ssu-dating#140]
## 에러 설명
첫 화면에 처음 접근할 때 화면이 깜빡거립니다.
~배경 이미지 width 값 설정이 안되어있어서 그런 것 같아요.(제가 잘못 봤네요)~

## 재현 방법

강력 새로고침 또는 처음 접근하는 경우

## 에러 화면
![Kapture 2023-12-20 at 01 44 25](https://github.com/yourssu/autumn-ssu-dating/assets/78731710/2662195b-3e5f-43e7-91f0-899acd88c359)

**Comment by nijuy** [comment]
네트워크 탭 보니까 용량하고 시간이 거의 1등이더라고요.. 뭔가 여길 건드리면 될 거 같은데 저도 방법을 더 찾아볼게요..!! 
![image](https://github.com/yourssu/autumn-ssu-dating/assets/87255462/a8888382-849b-49ad-b85b-7cd5711a5e68)

**Comment by intersoom** [comment]
유후 해당 문제의 해결법을 드디어 알았네요! 저희 성장했어요 >< @nijuy
