### ISSUE TITLE
[BUG] 이용권 받기 버튼 깜빡임

### ISSUE THREAD

**Issue by intersoom** [yourssu/autumn-ssu-dating#153]
## 에러 설명

처음에 화면 로드 될 때 pink -> white로 변경됩니다!

## 재현 방법

home 페이지에서 refresh 해보면 됩니다!

## 에러 화면

![Kapture 2023-12-21 at 01 46 43](https://github.com/yourssu/autumn-ssu-dating/assets/78731710/126eb64d-5ce8-4060-867b-706ea3964f64)

**Comment by intersoom** [comment]
@nijuy 보리한테 수정을 부탁드려도 될까용 ?!

**Comment by nijuy** [comment]
일단 원인은 `codeContact (비활성화 여부를 결정짓는 state) 초기값이 0이라 비활성화로 시작 ➡ 데이터 페칭되면 그에 맞게 수정하는 방식`이라 발생하는 문제고, 인지는 하고 있었는데 클라이언트에서 이전 codeContact를 저장해서 다음 Home 렌더링에 사용하기에는 슬랙에서 말씀드린 것처럼 조작 위험이 있을 거 같아서 조금 깜빡여도 서버값으로만 판단하게 했던거였어요~!

**Comment by intersoom** [comment]
허거헉헉헉 제가 놓쳤군요... 알겠숩니다 🥹
