### ISSUE TITLE
[REFACTOR] CI/CD 자동 배포 설정

### ISSUE THREAD

**Issue by intersoom** [yourssu/autumn-ssu-dating#165]
## AS-IS
현재 일일이 수동 배포 진행중입니다..

## TO-BE
해당 방식을 CI/CD를 통한 자동 배포 방식으로 개선했으면 좋겠습니다!

## TO-DO

- [ ] 서버에서 자동 배포 설정
- [ ] Github Action 작성

## 기타

여유가 날 때 한 번 같이 진행해보면 좋을 것 같아요 !

**Comment by nijuy** [comment]
동의 수동 배포가 정성스럽지만 이제 그만하고 싶어요...................................

숀이 깃허브 액션 사용량을 다 써서 당분간은 대부분 수동 배포해야한다고 했던거 같은데 그게 숨쉴에만 해당이 되는 얘긴지 / 아니라면 해결이 됐나 모르겠네요?!?! 오늘 물어보겟습니다
